---
- name: Configure Docker on EC2
  hosts: new
  become: true
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker container
      docker_container:
        name: zomato_container
        image: sreedhar8897/zomato:latest
        state: started
        restart_policy: always
        published_ports:
          - "3000:3000"
